### ISSUE TITLE
翻译字幕不正常显示

### ISSUE THREAD

**Issue by huangyedabiaoke6** [ouweiya/Dual-Caption-Blog#11]
播放视频前半段没翻译，后面突然把前面的翻译全挤一起，然后正常显示字幕，每个视频都这样，请问大佬怎么解决？

**Comment by carllx** [comment]
![](https://i.imgur.com/yISxq9J.png)

**Comment by Yee-YeeAssHaircut** [comment]
![螢幕擷取畫面 (7)](https://user-images.githubusercontent.com/104366051/206901611-90afe31e-42bd-438a-8ae8-a118e7a30433.png)

**Comment by mryangsj** [comment]
I have the same problem, waiting for the author to solve this.

**Comment by ouweiya** [comment]
This is caused by the YouTube translation algorithm. YouTube mistakenly merged all the subtitles into one sentence, so all the subtitles are output at the end of the video. I can't deal with this situation and can only wait for YouTube to fix it.

In the later stage, I added a third-party translation engine to solve this kind of problem.

**Comment by randyysr** [comment]
Same situation here.
