### ISSUE TITLE
The translation does not appear properly

### ISSUE THREAD

**Issue by saimow** [ouweiya/Dual-Caption-Blog#12]
the translated Text does not appear properly while watching the video and it appear suddenly all stacked at the end as shown on the image.
This problem don't occur on all Youtube videos.
Thank you for the amazing extension btw 🥇  

[the video](https://www.youtube.com/watch?v=QS2fnkMA46Q)
![22](https://user-images.githubusercontent.com/20516412/206931127-ecd455c2-34ee-4e16-9b4f-dbb683e2e781.PNG)

**Comment by ouweiya** [comment]
This is caused by the YouTube translation algorithm. YouTube mistakenly merged all the subtitles into one sentence, so all the subtitles are output at the end of the video. I can't deal with this situation and can only wait for YouTube to fix it.

In the later stage, I added a third-party translation engine to solve this kind of problem.

**Comment by saimow** [comment]
The problem does not occur any more. thanks!
